import re

with open('GithubDoc.md', 'r') as f:
    text = f.read()

# Remove form feeds (page breaks from pdftotext)
text = text.replace('\x0c', '')

# Remove standalone numbers that represent page numbers at the start/end of lines
text = re.sub(r'^\d+$\n', '', text, flags=re.MULTILINE)

# Remove the Table of contents generated by OCR (lines with multiple dots and a number)
text = re.sub(r'^.*\. \. \. \. \. \. \..*$\n', '', text, flags=re.MULTILINE)

# Fix line wrapping: if a line ends with a word and the next line starts with a word, join them
# We'll do this by replacing single newlines with spaces, but preserving double newlines
paragraphs = text.split('\n\n')
cleaned_paragraphs = []
for p in paragraphs:
    # replace single newlines with space, but avoid doing it for lists or headers
    if p.strip() and not p.strip().startswith(('#', '-', '*', '1.', '2.', '3.', '4.', '5.')):
        p = re.sub(r'(?<!\n)\n(?!\n)', ' ', p)
    cleaned_paragraphs.append(p)

cleaned_text = '\n\n'.join(cleaned_paragraphs)

# Format the title page roughly into APA style Markdown
apa_header = """# SISTEMA DE ANÁLISIS BIOMECÁNICO DE APOYO PARA JIUJITSU BRASILEÑO PARA LA ACADEMIA CORPO E MENTE

**Autor:** Santiago Borda Zambrana  
**Institución:** Universidad Privada de Santa Cruz de la Sierra (UPSA)  
**Facultad:** Facultad de Ingeniería  
**Carrera:** Ingeniería de Sistemas  
**Fecha:** 2026  

---
"""

# Try to strip the noisy beginning and append the clean header
match = re.search(r'ABSTRACT', cleaned_text)
if match:
    cleaned_text = apa_header + '\n## ' + cleaned_text[match.start():]

with open('GithubDoc.md', 'w') as f:
    f.write(cleaned_text)
