classDiagram
    direction LR
    
    class Usuario {
        +nombreCompleto: String
        +username: String
        +email: String
        +rol: RolEnum
        +avatarUrl: String
        +sucursalId: UUID
        +sucursalNombre: String
    }
    
    class CredencialesAutenticacion {
        +identificador: String
        +contraseña: String
    }
    
    class TokenAutenticacion {
        +token: String
        +tipo: String
        +expiraEn: Integer
        +usuario: Usuario
    }
    
    class InterfazAutenticacion {
        +solicitarAutenticacion(credenciales: CredencialesAutenticacion): TokenAutenticacion
        +validarFormatoCredenciales(credenciales: CredencialesAutenticacion): Boolean
        +mostrarMensajeError(mensaje: String): void
        +redirigirSegunRol(usuario: Usuario): void
    }
    
    class RolEnum {
        <<enumeration>>
        ALUMNO
        PROFESOR
        ADMINISTRADOR
    }
    
    CredencialesAutenticacion --> InterfazAutenticacion : proporciona
    InterfazAutenticacion --> TokenAutenticacion : retorna
    TokenAutenticacion --> Usuario : contiene
    Usuario --> RolEnum : tiene