sequenceDiagram
    autonumber
    actor Profesor
    participant System as :System

    Profesor->>System: iniciarSesion(email, password)
    activate System
    System-->>Profesor: tokenJWT
    deactivate System

    Profesor->>System: solicitarAnaliticaTatami(id_tecnica?)
    activate System
    System-->>Profesor: metricasGrupales
    deactivate System
    
    Note right of System: metricasGrupales DTO contiene:<br/>total_evaluaciones,<br/>tasa_aprobacion,<br/>debilidades_grupales[]
